---
language: python
sudo: false
env:
  global:
  - NETWORK_ENV=demo
  - ROLE=travis
  - TEAM=platform
  - PATH=$HOME/bin:$PATH
install:
- pip install -r requirements.txt
- make deps
- mkdir -p $HOME/bin
- ln -sv /bin/echo $HOME/bin/docker
script:
- ansible-playbook -i 127.0.0.1, -c local -s
    -e ssh_user=travis
    -e hostname=travis-tmp-host.demo.modcloth.com
    -vvvv
    ./test.yml
