---
- hosts: all
  roles:
  - role: hi.app
    hi_app_name: hi-long-running-app
    hi_app_type: long-running
    hi_app_docker_command:
      sh -c "while true ; do date ; sleep 10 ; done"
    hi_app_docker_repo: busybox
    hi_app_docker_args:
      - '--link memcached:memcached'
    hi_app_env:
      FOO: bar
    hi_app_docker_volumes:
      - { host: /var/log/foo, container: /var/logfoo, permissions: ro }

  # To be used with applications that should run on a schedule (e.g. a rake task)
  - role: hi.app
    hi_app_name: hi-cron-app
    hi_app_type: cron
    hi_app_docker_args:
      - '--link memcached:memcached'
    hi_app_docker_command: date
    hi_app_cron_schedule: '*/5 * * * *'
    hi_app_docker_repo: busybox
    hi_app_cron_stdin_command: date
    hi_app_env:
      FOO: bar
