---
- hosts: all
  roles:
  - role: modcloth.app
    modcloth_app_name: modcloth-long-running-app
    modcloth_app_type: long-running
    modcloth_app_docker_command: 'yes forever'
    modcloth_app_docker_repo: 'busybox'
    modcloth_app_env:
      FOO: 'bar'
  - role: modcloth.app
    modcloth_app_name: modcloth-cron-app
    modcloth_app_type: cron
    modcloth_app_docker_command: 'echo whatever'
    modcloth_app_docker_repo: 'busybox'
    modcloth_app_env:
      FOO: 'bar'
