---
- hosts: all
  roles:
  - role: modcloth.app
    modcloth_app_type: long-running
    modcloth_app_docker_command: 'env'
    modcloth_app_docker_repo: 'busybox'
    modcloth_app_env:
      SLEEPYTIME: '9999'
  - role: modcloth.app
    modcloth_app_type: cron
    modcloth_app_docker_command: 'env'
    modcloth_app_docker_repo: 'echo whatever'
    modcloth_app_env:
      FOO: 'bar'
