---
- name: write cron job wrapper
  template:
    src={{ hi_app_cron_wrapper_template }}
    dest=/usr/local/bin/{{ hi_app_name }}-cron-wrapper
    owner=root group=root mode=0755
  when: hi_app_cron_wrapper_template != ""
  register: hi_app_write_cron_wrapper

- name: create cron job
  cron:
    name={{ hi_app_name }}
    minute={{ hi_app_cron_schedule.split()[0] }}
    hour={{ hi_app_cron_schedule.split()[1] }}
    day={{ hi_app_cron_schedule.split()[2] }}
    month={{ hi_app_cron_schedule.split()[3] }}
    weekday={{ hi_app_cron_schedule.split()[4] }}
    job="run-one /usr/local/bin/{{ hi_app_name }}-cron-wrapper"
  when: hi_app_cron_wrapper_template != ""
  register: hi_app_create_cron_job

- name: Set up log rotation
  template:
    src={{ hi_app_cron_logrotate_template }}
    dest=/etc/logrotate.d/{{ hi_app_name }}
    mode=0644
    owner=root
    group=root
