---
- name: write upstart conf
  template:
    src={{ hi_app_upstart_conf_template }}
    dest=/etc/init/{{ hi_app_name }}.conf
    owner=root group=root mode=0644
  when: hi_app_upstart_conf_template != ""
  register: hi_app_write_upstart_conf

- name: stop app
  service: name={{ hi_app_name }} state=restarted
  when: hi_app_write_upstart_conf.changed
        or hi_app_write_etc_default_file.changed
        or hi_app_pull_container.changed

- name: start app
  service: name={{ hi_app_name }} state=started

- include: wait-healthcheck.yml
