---
- name: write systemd conf
  template:
    src: "{{ hi_app_systemd_conf_template }}"
    dest: /lib/systemd/system/{{ hi_app_name }}.service
    owner: root
    group: root
    mode: 0644
  when: hi_app_systemd_conf_template != ""
  register: hi_app_write_systemd_conf

- name: restart app
  systemd:
    name: "{{ hi_app_name }}"
    state: restarted
    daemon_reload: yes
  when: hi_app_write_systemd_conf.changed
        or hi_app_write_etc_default_file.changed
        or hi_app_pull_container.changed

- name: ensure app started
  systemd:
    name: "{{ hi_app_name }}"
    state: started
    enabled: true

- include_tasks: wait-healthcheck.yml
