---
- name: write etc default file
  template:
    src: "{{ hi_app_etc_default_template }}"
    dest: /etc/default/{{ hi_app_name }}
    owner: root
    group: root
    mode: 0644
  when: hi_app_etc_default_template != ""
  register: hi_app_write_etc_default_file

- name: install docker-py and requests on host
  pip:
    name:
      - docker-py
      - requests
    executable: "{{ hi_app_pip_location }}"

- name: docker login
  docker_login:
    username: "{{ hi_app_docker_registry.username }}"
    password: "{{ hi_app_docker_registry.password }}"
    registry: "{{ hi_app_docker_registry.registry }}"
    email: "{{ hi_app_docker_registry.email }}"
  changed_when: false

- name: pull container
  docker_image:
    name: "{{ hi_app_docker_repo }}:{{ hi_app_docker_tag }}"
    state: present
    force: "{{ hi_app_docker_force_pull }}"
  when: hi_app_docker_repo != "" and hi_app_docker_tag != ""
  register: hi_app_pull_container

- include_tasks: cron.yml
  when: hi_app_type == "cron"
  register: hi_app_type_cron

- include_tasks: long-running.yml
  when: hi_app_type == "long-running"
  register: hi_app_type_long_running
