---
- name: install pip package required for uri module
  pip: name=httplib2 state=present
  when: hi_app_healthcheck_enabled|bool

- name: await healthy
  uri:
    url: "{{ hi_app_healthcheck_url }}"
    timeout: "{{ hi_app_healthcheck_timeout }}"
  register: result
  retries: 30 # currently not configurable due to https://github.com/ansible/ansible/issues/5865
  delay:  "{{ hi_app_healthcheck_delay|int }}"
  until: result.status is defined and result.status < 400 and result.status >= 200
  when: hi_app_healthcheck_enabled|bool
