---
- name: install pip package required for uri module
  pip: name=httplib2 state=present
  when: modcloth_app_healthcheck_enabled|bool

- name: await healthy
  uri:
    url: "{{ modcloth_app_healthcheck_url }}"
    timeout: "{{ modcloth_app_healthcheck_timeout }}"
  register: result
  retries: "{{ modcloth_app_healthcheck_retries }}"
  delay: "{{ modcloth_app_healthcheck_delay }}"
  until: result.status < 400 and result.status >= 200
  when: modcloth_app_healthcheck_enabled|bool
